version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn run dev
    volumes:
      - .:/app:delegated
    ports:
      - 3000:3000
    labels:
      lagoon.type: node
    environment:
      - LAGOON=LAGOON
